FROM alpine:3.21@sha256:81ec32e1e073303f1591af7725ca32446d44d12907c1f4e2851a95031faaec99
RUN apk add --no-cache ca-certificates curl
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/vault-backup-cluster /vault-backup-cluster
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD curl -fsS http://127.0.0.1:8080/healthz || exit 1
USER 65532:65532
EXPOSE 8080
ENTRYPOINT ["/vault-backup-cluster"]
